### ISSUE TITLE
Creating Multiple SSH Security Groups

### ISSUE THREAD

**Issue by GavinBurris42** [awslabs/aws-simple-ec2-cli#78]
**Describe the bug**
A concise description of what the bug is.
When given options to create security groups in the simple-ec2 CLI tool, the user is given the option to create a new security group that enables SSH. However, if they have already created a security group that enables SSH simple-ec2 will return an error as the security groups GroupName field is hardcoded, instead of having a unique value. 

**Steps to reproduce**
A step-by-step description on how to reproduce the problem.
1. Use interactive mode on simple-ec2. 
2. In the security group selection step, choose the option to create a new security group that enables SSH. 
3. If this was the first time selecting the "create a new security group that enables SSH" option, then repeat steps 1 and 2.

**Expected outcome**
A concise description of what you expected to happen.
One of the following:
1. Multiple SSH security groups can be created
2. Only one SSH security group can be created, and the option to create more is removed

**Application Logs**
The log output when experiencing the issue.
Creating new security group for SSH failed: InvalidGroup.Duplicate: The security group 'simple-ec2 SSH' already exists for VPC 'vpc-07a5eb4bd9c8f9fcd' status code: 400, request id: 92971c58-1945-4afb-b92c-3347de5c175a

**Environment**
Simple-EC2 using Mac terminal

* App Version:
* OS/Arch:

**Comment by brycahta** [comment]
The use case I had in mind was creating **multiple instances** in the same VPC. Maybe I want to be able to ssh to both during development, but then update SG permissions on one instance down the road. If we remove creating ssh-only SG _per instance_, then users will either need to create SG ahead of time (not simple!) or create/associate a new SG when it comes time to update the instance permissions (if they reused existing). Also, creating a new simple-ec2 SG would only add flexibility because users would still be able to choose an existing simple-ec2 SG if it aligns with their use case. I don't know how practical this or other use cases involving, but I'm erring on the side of flexibility due to that uncertainty.

Last note, these simple-ec2 SGs are just starting points and aren't guaranteed to stay the same. Correct me if I'm wrong, but I think if I requested a _simple-ec2 instance_ and update its SG to remove ssh-only, then try to request another _simple-ec2 instance_ there's a chance I can neither select nor create an ssh-only SG.

**Comment by snay2** [comment]
Great points, thanks @brycahta!

Given that we have at least one well-reasoned usecase for wanting multiple simple-ec2 SGs, I say we go ahead with allowing them and using unique names for each.

**Comment by snay2** [comment]
This has been released in [v0.8.2](https://github.com/awslabs/aws-simple-ec2-cli/releases/tag/v0.8.2).
